CREATE TABLE BOOKS {
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    BOOK_NAME VARCHAR(100);
    BOOK_AUTHOR VARCHAR(100);
    BOOK_RESUME VARCHAR(1000);
    RELEASE_PRICE TIMESTAMP;
    PRICE NUMERIC(20,2);
    ISBN VARCHAR(50);
    };

CREATE TABLE CLIENTS {
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENT_NAME VARCHAR(100);
    EMAIL VARCHAR(100);
    CPF VARCHAR(40);
    PHONE_NUMBER varchar(20);
    };